// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TrainingApp.Infrastructure;

#nullable disable

namespace TrainingApp.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("TrainingApp.Application.Entities.Excercise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("ExcersiceType")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsBuiltIn")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Excercises", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("cf56841e-ef9a-4c15-aab8-3cf2487e76af"),
                            ExcersiceType = 0,
                            IsBuiltIn = true,
                            Name = "Pullups"
                        },
                        new
                        {
                            Id = new Guid("42efd1bf-124c-482e-bbb4-12dd1a9f9b7b"),
                            ExcersiceType = 0,
                            IsBuiltIn = true,
                            Name = "Ab curl"
                        },
                        new
                        {
                            Id = new Guid("982d6450-8384-4535-b3a7-d4371f9acba5"),
                            ExcersiceType = 1,
                            IsBuiltIn = false,
                            Name = "Custom 1"
                        });
                });

            modelBuilder.Entity("TrainingApp.Application.Entities.Routine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("DateTimes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Routines", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("64986f99-5c45-4725-b0aa-c8ae1e0c42ec"),
                            DateTimes = "",
                            Name = "Abs"
                        },
                        new
                        {
                            Id = new Guid("89413f12-9a28-486b-a2e0-13b9f6f936cc"),
                            DateTimes = "",
                            Name = "Pull"
                        });
                });

            modelBuilder.Entity("TrainingApp.Application.Entities.RoutineExcersices", b =>
                {
                    b.Property<Guid>("RoutineId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ExcerciseId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.HasKey("RoutineId", "ExcerciseId");

                    b.HasIndex("ExcerciseId");

                    b.ToTable("RoutineExcercises", (string)null);
                });

            modelBuilder.Entity("TrainingApp.Application.Entities.Set", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ExcerciseId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Measure")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Reps")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("WorkoutId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExcerciseId");

                    b.HasIndex("WorkoutId", "ExcerciseId");

                    b.ToTable("Sets", (string)null);
                });

            modelBuilder.Entity("TrainingApp.Application.Entities.Workout", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDone")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Workouts", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("32ad43e3-c931-4b89-a20a-35e3d15474ab"),
                            Date = new DateTime(2023, 5, 14, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDone = false,
                            Name = "Abs"
                        },
                        new
                        {
                            Id = new Guid("b1d6ef22-030d-4d46-99d9-2513b4085795"),
                            Date = new DateTime(2023, 5, 14, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDone = false,
                            Name = "Pull"
                        },
                        new
                        {
                            Id = new Guid("a8adfce9-2680-434a-a652-6e84b98c1023"),
                            Date = new DateTime(2023, 5, 13, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDone = true,
                            Name = "Abs"
                        });
                });

            modelBuilder.Entity("TrainingApp.Application.Entities.WorkoutExcersices", b =>
                {
                    b.Property<Guid>("WorkoutId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ExcerciseId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.HasKey("WorkoutId", "ExcerciseId");

                    b.HasIndex("ExcerciseId");

                    b.ToTable("WorkoutExcercises", (string)null);
                });

            modelBuilder.Entity("TrainingApp.Application.Entities.RoutineExcersices", b =>
                {
                    b.HasOne("TrainingApp.Application.Entities.Excercise", "Excercise")
                        .WithMany("RoutineExcersices")
                        .HasForeignKey("ExcerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrainingApp.Application.Entities.Routine", "Routine")
                        .WithMany("RoutineExcersices")
                        .HasForeignKey("RoutineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Excercise");

                    b.Navigation("Routine");
                });

            modelBuilder.Entity("TrainingApp.Application.Entities.Set", b =>
                {
                    b.HasOne("TrainingApp.Application.Entities.Excercise", "Excercise")
                        .WithMany()
                        .HasForeignKey("ExcerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrainingApp.Application.Entities.Workout", "Workout")
                        .WithMany()
                        .HasForeignKey("WorkoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrainingApp.Application.Entities.WorkoutExcersices", "WorkoutExcercises")
                        .WithMany("Sets")
                        .HasForeignKey("WorkoutId", "ExcerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Excercise");

                    b.Navigation("Workout");

                    b.Navigation("WorkoutExcercises");
                });

            modelBuilder.Entity("TrainingApp.Application.Entities.WorkoutExcersices", b =>
                {
                    b.HasOne("TrainingApp.Application.Entities.Excercise", "Excercise")
                        .WithMany("WorkoutExcersices")
                        .HasForeignKey("ExcerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrainingApp.Application.Entities.Workout", "Workout")
                        .WithMany("WorkoutExcersices")
                        .HasForeignKey("WorkoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Excercise");

                    b.Navigation("Workout");
                });

            modelBuilder.Entity("TrainingApp.Application.Entities.Excercise", b =>
                {
                    b.Navigation("RoutineExcersices");

                    b.Navigation("WorkoutExcersices");
                });

            modelBuilder.Entity("TrainingApp.Application.Entities.Routine", b =>
                {
                    b.Navigation("RoutineExcersices");
                });

            modelBuilder.Entity("TrainingApp.Application.Entities.Workout", b =>
                {
                    b.Navigation("WorkoutExcersices");
                });

            modelBuilder.Entity("TrainingApp.Application.Entities.WorkoutExcersices", b =>
                {
                    b.Navigation("Sets");
                });
#pragma warning restore 612, 618
        }
    }
}
